-- ✅ Corrige e aplica Opção B (Grupo fechado 9 pessoas) + índice isActive do ReferralLevelConfig
-- Observação: Postgres NÃO tem "ADD CONSTRAINT IF NOT EXISTS", então usamos DO $$ ... $$

-- 0) Índice faltante do drift (ReferralLevelConfig.isActive)
CREATE INDEX IF NOT EXISTS "ReferralLevelConfig_isActive_idx"
  ON "public"."ReferralLevelConfig"("isActive");

-- 1) CashbackTransaction: adicionar colunas (auditoria grupo/posição)
ALTER TABLE "public"."CashbackTransaction"
  ADD COLUMN IF NOT EXISTS "referralGroupId" INTEGER;

ALTER TABLE "public"."CashbackTransaction"
  ADD COLUMN IF NOT EXISTS "referralPosition" INTEGER;

-- 2) ReferralGroup
CREATE TABLE IF NOT EXISTS "public"."ReferralGroup" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "maxMembers" INTEGER NOT NULL DEFAULT 9,
  "isClosed" BOOLEAN NOT NULL DEFAULT false,
  "cashbackSuspended" BOOLEAN NOT NULL DEFAULT false,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "closedAt" TIMESTAMP(3),
  "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS "ReferralGroup_createdAt_idx" ON "public"."ReferralGroup"("createdAt");
CREATE INDEX IF NOT EXISTS "ReferralGroup_isClosed_idx" ON "public"."ReferralGroup"("isClosed");
CREATE INDEX IF NOT EXISTS "ReferralGroup_cashbackSuspended_idx" ON "public"."ReferralGroup"("cashbackSuspended");

-- 3) ReferralGroupMember
CREATE TABLE IF NOT EXISTS "public"."ReferralGroupMember" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "groupId" INTEGER NOT NULL,
  "userId" INTEGER NOT NULL,
  "position" INTEGER NOT NULL,
  "joinedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Uniques (equivalentes ao Prisma)
CREATE UNIQUE INDEX IF NOT EXISTS "ReferralGroupMember_groupId_userId_key"
  ON "public"."ReferralGroupMember"("groupId","userId");

CREATE UNIQUE INDEX IF NOT EXISTS "ReferralGroupMember_groupId_position_key"
  ON "public"."ReferralGroupMember"("groupId","position");

-- Índices
CREATE INDEX IF NOT EXISTS "ReferralGroupMember_userId_idx" ON "public"."ReferralGroupMember"("userId");
CREATE INDEX IF NOT EXISTS "ReferralGroupMember_groupId_idx" ON "public"."ReferralGroupMember"("groupId");
CREATE INDEX IF NOT EXISTS "ReferralGroupMember_position_idx" ON "public"."ReferralGroupMember"("position");

-- FKs (sem IF NOT EXISTS -> usamos DO/pg_constraint)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint c
    JOIN pg_class t ON t.oid = c.conrelid
    JOIN pg_namespace n ON n.oid = t.relnamespace
    WHERE c.conname = 'ReferralGroupMember_groupId_fkey'
      AND n.nspname = 'public'
      AND t.relname = 'ReferralGroupMember'
  ) THEN
    ALTER TABLE "public"."ReferralGroupMember"
      ADD CONSTRAINT "ReferralGroupMember_groupId_fkey"
      FOREIGN KEY ("groupId") REFERENCES "public"."ReferralGroup"("id")
      ON DELETE RESTRICT ON UPDATE CASCADE;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint c
    JOIN pg_class t ON t.oid = c.conrelid
    JOIN pg_namespace n ON n.oid = t.relnamespace
    WHERE c.conname = 'ReferralGroupMember_userId_fkey'
      AND n.nspname = 'public'
      AND t.relname = 'ReferralGroupMember'
  ) THEN
    ALTER TABLE "public"."ReferralGroupMember"
      ADD CONSTRAINT "ReferralGroupMember_userId_fkey"
      FOREIGN KEY ("userId") REFERENCES "public"."User"("id")
      ON DELETE RESTRICT ON UPDATE CASCADE;
  END IF;
END $$;

-- 4) ReferralPositionBonusConfig (config por posição e tipo)
CREATE TABLE IF NOT EXISTS "public"."ReferralPositionBonusConfig" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "position" INTEGER NOT NULL,
  "type" "public"."BonusType" NOT NULL,
  "amount" DOUBLE PRECISION NOT NULL,
  "isActive" BOOLEAN NOT NULL DEFAULT true,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS "ReferralPositionBonusConfig_position_type_key"
  ON "public"."ReferralPositionBonusConfig"("position","type");

CREATE INDEX IF NOT EXISTS "ReferralPositionBonusConfig_position_idx"
  ON "public"."ReferralPositionBonusConfig"("position");

CREATE INDEX IF NOT EXISTS "ReferralPositionBonusConfig_type_idx"
  ON "public"."ReferralPositionBonusConfig"("type");

-- 5) FK CashbackTransaction -> ReferralGroup (SET NULL)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint c
    JOIN pg_class t ON t.oid = c.conrelid
    JOIN pg_namespace n ON n.oid = t.relnamespace
    WHERE c.conname = 'CashbackTransaction_referralGroupId_fkey'
      AND n.nspname = 'public'
      AND t.relname = 'CashbackTransaction'
  ) THEN
    ALTER TABLE "public"."CashbackTransaction"
      ADD CONSTRAINT "CashbackTransaction_referralGroupId_fkey"
      FOREIGN KEY ("referralGroupId") REFERENCES "public"."ReferralGroup"("id")
      ON DELETE SET NULL ON UPDATE CASCADE;
  END IF;
END $$;

-- 6) Índices novos no CashbackTransaction
CREATE INDEX IF NOT EXISTS "CashbackTransaction_referralGroupId_idx"
  ON "public"."CashbackTransaction"("referralGroupId");

CREATE INDEX IF NOT EXISTS "CashbackTransaction_referralPosition_idx"
  ON "public"."CashbackTransaction"("referralPosition");
