-- =====================================================================================
-- MIGRATION (MANUAL / IDEMPOTENTE)
-- Opção B: Grupo fechado (9 pessoas) + Config por POSIÇÃO + rastreio em CashbackTransaction
-- + Reconciliação de índice ReferralLevelConfig.isActive
--
-- IMPORTANTE:
-- - NÃO usa "ADD CONSTRAINT IF NOT EXISTS" (Postgres não suporta).
-- - Seguro para rodar mesmo se parte já tiver sido aplicada anteriormente.
-- =====================================================================================

-- ---------------------------------------------------------------------
-- 0) ReferralLevelConfig: índice isActive (reconciliação)
-- ---------------------------------------------------------------------
DO $$ BEGIN
  IF EXISTS (
    SELECT 1
    FROM information_schema.tables
    WHERE table_schema='public' AND table_name='ReferralLevelConfig'
  ) THEN
    IF NOT EXISTS (
      SELECT 1 FROM pg_indexes
      WHERE schemaname='public' AND indexname='ReferralLevelConfig_isActive_idx'
    ) THEN
      CREATE INDEX "ReferralLevelConfig_isActive_idx"
        ON public."ReferralLevelConfig" ("isActive");
    END IF;
  END IF;
END $$;

-- ---------------------------------------------------------------------
-- 1) CashbackTransaction: adicionar colunas (grupo/posição)
-- ---------------------------------------------------------------------
ALTER TABLE public."CashbackTransaction"
  ADD COLUMN IF NOT EXISTS "referralGroupId" INTEGER,
  ADD COLUMN IF NOT EXISTS "referralPosition" INTEGER;

-- Índices para novas colunas
CREATE INDEX IF NOT EXISTS "CashbackTransaction_referralGroupId_idx"
  ON public."CashbackTransaction" ("referralGroupId");

CREATE INDEX IF NOT EXISTS "CashbackTransaction_referralPosition_idx"
  ON public."CashbackTransaction" ("referralPosition");

-- ---------------------------------------------------------------------
-- 2) Tabela ReferralGroup (grupo fechado: 9 membros)
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public."ReferralGroup" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "maxMembers" INTEGER NOT NULL DEFAULT 9,
  "isClosed" BOOLEAN NOT NULL DEFAULT false,
  "cashbackSuspended" BOOLEAN NOT NULL DEFAULT false,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "closedAt" TIMESTAMP(3),
  "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS "ReferralGroup_createdAt_idx"
  ON public."ReferralGroup" ("createdAt");

CREATE INDEX IF NOT EXISTS "ReferralGroup_isClosed_idx"
  ON public."ReferralGroup" ("isClosed");

CREATE INDEX IF NOT EXISTS "ReferralGroup_cashbackSuspended_idx"
  ON public."ReferralGroup" ("cashbackSuspended");

-- ---------------------------------------------------------------------
-- 3) Tabela ReferralGroupMember (posições 1..9)
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public."ReferralGroupMember" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "groupId" INTEGER NOT NULL,
  "userId" INTEGER NOT NULL,
  "position" INTEGER NOT NULL,
  "joinedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Uniques equivalentes ao Prisma
CREATE UNIQUE INDEX IF NOT EXISTS "ReferralGroupMember_groupId_userId_key"
  ON public."ReferralGroupMember" ("groupId","userId");

CREATE UNIQUE INDEX IF NOT EXISTS "ReferralGroupMember_groupId_position_key"
  ON public."ReferralGroupMember" ("groupId","position");

-- Índices úteis
CREATE INDEX IF NOT EXISTS "ReferralGroupMember_userId_idx"
  ON public."ReferralGroupMember" ("userId");

CREATE INDEX IF NOT EXISTS "ReferralGroupMember_groupId_idx"
  ON public."ReferralGroupMember" ("groupId");

CREATE INDEX IF NOT EXISTS "ReferralGroupMember_position_idx"
  ON public."ReferralGroupMember" ("position");

-- FK groupId -> ReferralGroup(id)
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM information_schema.table_constraints
    WHERE constraint_schema='public'
      AND table_name='ReferralGroupMember'
      AND constraint_name='ReferralGroupMember_groupId_fkey'
  ) THEN
    ALTER TABLE public."ReferralGroupMember"
      ADD CONSTRAINT "ReferralGroupMember_groupId_fkey"
      FOREIGN KEY ("groupId") REFERENCES public."ReferralGroup"("id")
      ON DELETE RESTRICT ON UPDATE CASCADE;
  END IF;
END $$;

-- FK userId -> User(id)
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM information_schema.table_constraints
    WHERE constraint_schema='public'
      AND table_name='ReferralGroupMember'
      AND constraint_name='ReferralGroupMember_userId_fkey'
  ) THEN
    ALTER TABLE public."ReferralGroupMember"
      ADD CONSTRAINT "ReferralGroupMember_userId_fkey"
      FOREIGN KEY ("userId") REFERENCES public."User"("id")
      ON DELETE RESTRICT ON UPDATE CASCADE;
  END IF;
END $$;

-- ---------------------------------------------------------------------
-- 4) ReferralPositionBonusConfig (por POSIÇÃO e por TIPO: UNIQUE/RECURRENT)
--    Usa enum public."BonusType" existente
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public."ReferralPositionBonusConfig" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "position" INTEGER NOT NULL,
  "type" public."BonusType" NOT NULL,
  "amount" DOUBLE PRECISION NOT NULL,
  "isActive" BOOLEAN NOT NULL DEFAULT true,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS "ReferralPositionBonusConfig_position_type_key"
  ON public."ReferralPositionBonusConfig" ("position","type");

CREATE INDEX IF NOT EXISTS "ReferralPositionBonusConfig_position_idx"
  ON public."ReferralPositionBonusConfig" ("position");

CREATE INDEX IF NOT EXISTS "ReferralPositionBonusConfig_type_idx"
  ON public."ReferralPositionBonusConfig" ("type");

-- ---------------------------------------------------------------------
-- 5) FK CashbackTransaction.referralGroupId -> ReferralGroup(id) (SET NULL)
-- ---------------------------------------------------------------------
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM information_schema.table_constraints
    WHERE constraint_schema='public'
      AND table_name='CashbackTransaction'
      AND constraint_name='CashbackTransaction_referralGroupId_fkey'
  ) THEN
    ALTER TABLE public."CashbackTransaction"
      ADD CONSTRAINT "CashbackTransaction_referralGroupId_fkey"
      FOREIGN KEY ("referralGroupId") REFERENCES public."ReferralGroup"("id")
      ON DELETE SET NULL ON UPDATE CASCADE;
  END IF;
END $$;

-- =====================================================================================
-- FIM
-- =====================================================================================
